const mongoose = require('mongoose');

const reportSchema = new mongoose.Schema({
  generatedBy: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User',
    required: [true, 'Report must be generated by a user'],
  },
  patient: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'Patient',
  },
  type: {
    type: String,
    enum: ['medication', 'routine', 'recognition', 'weekly_summary', 'monthly_overview', 'emergency', 'compliance', 'system'],
    required: [true, 'Please provide report type'],
  },
  title: {
    type: String,
    required: [true, 'Please provide report title'],
  },
  period: {
    from: Date,
    to: Date,
  },
  format: {
    type: String,
    enum: ['pdf', 'excel'],
    default: 'pdf',
  },
  filePath: {
    type: String,
  },
  status: {
    type: String,
    enum: ['processing', 'ready', 'failed'],
    default: 'processing',
  },
  data: mongoose.Schema.Types.Mixed,
  // Flexible JSON for report data
  createdAt: {
    type: Date,
    default: Date.now,
  },
});

module.exports = mongoose.model('Report', reportSchema);
